name: Build and Publish Docker Images
'on':
  push:
    paths:
    - dataset/*/out/reproduction/gpt-4o-mini_augmented_prompt
    branches:
    - '**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: dataset
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push cd5bb39f43e4570b875027073da3d4e43349ead1
      uses: docker/build-push-action@v2
      with:
        context: dataset/cd5bb39f43e4570b875027073da3d4e43349ead1/out/reproduction/gpt-4o-mini_augmented_prompt
        file: dataset/cd5bb39f43e4570b875027073da3d4e43349ead1/out/reproduction/gpt-4o-mini_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/gpt-4o-mini_augmented_prompt-cd5bb39f43e4570b875027073da3d4e43349ead1-reproduction
    - name: Build and push ff8b5b61548d50cf60b77784a181e917cb35033b
      uses: docker/build-push-action@v2
      with:
        context: dataset/ff8b5b61548d50cf60b77784a181e917cb35033b/out/reproduction/gpt-4o-mini_augmented_prompt
        file: dataset/ff8b5b61548d50cf60b77784a181e917cb35033b/out/reproduction/gpt-4o-mini_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/gpt-4o-mini_augmented_prompt-ff8b5b61548d50cf60b77784a181e917cb35033b-reproduction
    - name: Build and push 6c53cd904bd66fc79af8687571e607c259226b81
      uses: docker/build-push-action@v2
      with:
        context: dataset/6c53cd904bd66fc79af8687571e607c259226b81/out/reproduction/gpt-4o-mini_augmented_prompt
        file: dataset/6c53cd904bd66fc79af8687571e607c259226b81/out/reproduction/gpt-4o-mini_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/gpt-4o-mini_augmented_prompt-6c53cd904bd66fc79af8687571e607c259226b81-reproduction
    - name: Build and push 5769bdad76925da568294cb8a40e7d4469699ac3
      uses: docker/build-push-action@v2
      with:
        context: dataset/5769bdad76925da568294cb8a40e7d4469699ac3/out/reproduction/gpt-4o-mini_augmented_prompt
        file: dataset/5769bdad76925da568294cb8a40e7d4469699ac3/out/reproduction/gpt-4o-mini_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/gpt-4o-mini_augmented_prompt-5769bdad76925da568294cb8a40e7d4469699ac3-reproduction
    - name: Build and push 0a11c04038eae517540051dbf51f7f26b7221f20
      uses: docker/build-push-action@v2
      with:
        context: dataset/0a11c04038eae517540051dbf51f7f26b7221f20/out/reproduction/gpt-4o-mini_augmented_prompt
        file: dataset/0a11c04038eae517540051dbf51f7f26b7221f20/out/reproduction/gpt-4o-mini_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/gpt-4o-mini_augmented_prompt-0a11c04038eae517540051dbf51f7f26b7221f20-reproduction
    - name: Build and push 36859167815292f279e570d39dd2ddbcf1622dc6
      uses: docker/build-push-action@v2
      with:
        context: dataset/36859167815292f279e570d39dd2ddbcf1622dc6/out/reproduction/gpt-4o-mini_augmented_prompt
        file: dataset/36859167815292f279e570d39dd2ddbcf1622dc6/out/reproduction/gpt-4o-mini_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/gpt-4o-mini_augmented_prompt-36859167815292f279e570d39dd2ddbcf1622dc6-reproduction
