name: Build and Publish Docker Images
'on':
  push:
    paths:
    - dataset/*/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
    branches:
    - '**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: dataset
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push 40feecdd9c649644668d7c84bb87b73a2b2723ca
      uses: docker/build-push-action@v2
      with:
        context: dataset/40feecdd9c649644668d7c84bb87b73a2b2723ca/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/40feecdd9c649644668d7c84bb87b73a2b2723ca/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-40feecdd9c649644668d7c84bb87b73a2b2723ca-reproduction
    - name: Build and push 6c53cd904bd66fc79af8687571e607c259226b81
      uses: docker/build-push-action@v2
      with:
        context: dataset/6c53cd904bd66fc79af8687571e607c259226b81/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/6c53cd904bd66fc79af8687571e607c259226b81/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-6c53cd904bd66fc79af8687571e607c259226b81-reproduction
    - name: Build and push 18eff0121ded81b30af0924676407bfc663e6557
      uses: docker/build-push-action@v2
      with:
        context: dataset/18eff0121ded81b30af0924676407bfc663e6557/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/18eff0121ded81b30af0924676407bfc663e6557/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-18eff0121ded81b30af0924676407bfc663e6557-reproduction
    - name: Build and push 24d4a90ec1b375751e71f33d18949405c9529d77
      uses: docker/build-push-action@v2
      with:
        context: dataset/24d4a90ec1b375751e71f33d18949405c9529d77/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/24d4a90ec1b375751e71f33d18949405c9529d77/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-24d4a90ec1b375751e71f33d18949405c9529d77-reproduction
    - name: Build and push dbdc7d2c4a28a8d65edcd0cdece91c0bc357b869
      uses: docker/build-push-action@v2
      with:
        context: dataset/dbdc7d2c4a28a8d65edcd0cdece91c0bc357b869/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/dbdc7d2c4a28a8d65edcd0cdece91c0bc357b869/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-dbdc7d2c4a28a8d65edcd0cdece91c0bc357b869-reproduction
    - name: Build and push 979d6237a50840cd925cc1a33c415ffbbbc42846
      uses: docker/build-push-action@v2
      with:
        context: dataset/979d6237a50840cd925cc1a33c415ffbbbc42846/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/979d6237a50840cd925cc1a33c415ffbbbc42846/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-979d6237a50840cd925cc1a33c415ffbbbc42846-reproduction
    - name: Build and push 5769bdad76925da568294cb8a40e7d4469699ac3
      uses: docker/build-push-action@v2
      with:
        context: dataset/5769bdad76925da568294cb8a40e7d4469699ac3/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/5769bdad76925da568294cb8a40e7d4469699ac3/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-5769bdad76925da568294cb8a40e7d4469699ac3-reproduction
    - name: Build and push 06c5386831e97e94d9b9fd155d3ea4aa8711c4e7
      uses: docker/build-push-action@v2
      with:
        context: dataset/06c5386831e97e94d9b9fd155d3ea4aa8711c4e7/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/06c5386831e97e94d9b9fd155d3ea4aa8711c4e7/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-06c5386831e97e94d9b9fd155d3ea4aa8711c4e7-reproduction
    - name: Build and push 441f7f07d9265cc1d4c4f369ee6524973d9c6e17
      uses: docker/build-push-action@v2
      with:
        context: dataset/441f7f07d9265cc1d4c4f369ee6524973d9c6e17/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/441f7f07d9265cc1d4c4f369ee6524973d9c6e17/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-441f7f07d9265cc1d4c4f369ee6524973d9c6e17-reproduction
    - name: Build and push 36859167815292f279e570d39dd2ddbcf1622dc6
      uses: docker/build-push-action@v2
      with:
        context: dataset/36859167815292f279e570d39dd2ddbcf1622dc6/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/36859167815292f279e570d39dd2ddbcf1622dc6/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-36859167815292f279e570d39dd2ddbcf1622dc6-reproduction
    - name: Build and push 500d9c021d34b307b1a70d3f29fb7f9b5ab9d1a6
      uses: docker/build-push-action@v2
      with:
        context: dataset/500d9c021d34b307b1a70d3f29fb7f9b5ab9d1a6/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/500d9c021d34b307b1a70d3f29fb7f9b5ab9d1a6/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-500d9c021d34b307b1a70d3f29fb7f9b5ab9d1a6-reproduction
    - name: Build and push 8ab7a7214f9ac1d130b416fae7280cfda533a54f
      uses: docker/build-push-action@v2
      with:
        context: dataset/8ab7a7214f9ac1d130b416fae7280cfda533a54f/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/8ab7a7214f9ac1d130b416fae7280cfda533a54f/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-8ab7a7214f9ac1d130b416fae7280cfda533a54f-reproduction
    - name: Build and push 88c1f903cede03ff371059cdaf009dab12007043
      uses: docker/build-push-action@v2
      with:
        context: dataset/88c1f903cede03ff371059cdaf009dab12007043/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/88c1f903cede03ff371059cdaf009dab12007043/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-88c1f903cede03ff371059cdaf009dab12007043-reproduction
    - name: Build and push c09896887acf0fe59320e01145a7034cd8d4e326
      uses: docker/build-push-action@v2
      with:
        context: dataset/c09896887acf0fe59320e01145a7034cd8d4e326/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/c09896887acf0fe59320e01145a7034cd8d4e326/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-c09896887acf0fe59320e01145a7034cd8d4e326-reproduction
    - name: Build and push 54857351e0b0a655970d7e2ccdb67f175cc5d688
      uses: docker/build-push-action@v2
      with:
        context: dataset/54857351e0b0a655970d7e2ccdb67f175cc5d688/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/54857351e0b0a655970d7e2ccdb67f175cc5d688/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-54857351e0b0a655970d7e2ccdb67f175cc5d688-reproduction
    - name: Build and push b8f92ff37d1aed054d8320283fd6d6a492703a55
      uses: docker/build-push-action@v2
      with:
        context: dataset/b8f92ff37d1aed054d8320283fd6d6a492703a55/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/b8f92ff37d1aed054d8320283fd6d6a492703a55/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-b8f92ff37d1aed054d8320283fd6d6a492703a55-reproduction
    - name: Build and push bd3ce213e2771c6ef7817c80818807a757d4e94a
      uses: docker/build-push-action@v2
      with:
        context: dataset/bd3ce213e2771c6ef7817c80818807a757d4e94a/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/bd3ce213e2771c6ef7817c80818807a757d4e94a/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-bd3ce213e2771c6ef7817c80818807a757d4e94a-reproduction
    - name: Build and push 0a11c04038eae517540051dbf51f7f26b7221f20
      uses: docker/build-push-action@v2
      with:
        context: dataset/0a11c04038eae517540051dbf51f7f26b7221f20/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/0a11c04038eae517540051dbf51f7f26b7221f20/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-0a11c04038eae517540051dbf51f7f26b7221f20-reproduction
    - name: Build and push 42a220bd546d293886df0d5e3892cc3ff82f1091
      uses: docker/build-push-action@v2
      with:
        context: dataset/42a220bd546d293886df0d5e3892cc3ff82f1091/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/42a220bd546d293886df0d5e3892cc3ff82f1091/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-42a220bd546d293886df0d5e3892cc3ff82f1091-reproduction
    - name: Build and push 07e4b2894bc68cd3bb1892beaa13ec353564dcf1
      uses: docker/build-push-action@v2
      with:
        context: dataset/07e4b2894bc68cd3bb1892beaa13ec353564dcf1/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/07e4b2894bc68cd3bb1892beaa13ec353564dcf1/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-07e4b2894bc68cd3bb1892beaa13ec353564dcf1-reproduction
    - name: Build and push 3ff575ae202cdf76ddfa8a4228a1711a6fa1e921
      uses: docker/build-push-action@v2
      with:
        context: dataset/3ff575ae202cdf76ddfa8a4228a1711a6fa1e921/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/3ff575ae202cdf76ddfa8a4228a1711a6fa1e921/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-3ff575ae202cdf76ddfa8a4228a1711a6fa1e921-reproduction
    - name: Build and push e40f76d1150d41821ccfd72e9dd3fabbc8763c1e
      uses: docker/build-push-action@v2
      with:
        context: dataset/e40f76d1150d41821ccfd72e9dd3fabbc8763c1e/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/e40f76d1150d41821ccfd72e9dd3fabbc8763c1e/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-e40f76d1150d41821ccfd72e9dd3fabbc8763c1e-reproduction
    - name: Build and push 6ad104c4fb9263ad1bb29e6b33618b8225efd92d
      uses: docker/build-push-action@v2
      with:
        context: dataset/6ad104c4fb9263ad1bb29e6b33618b8225efd92d/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/6ad104c4fb9263ad1bb29e6b33618b8225efd92d/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-6ad104c4fb9263ad1bb29e6b33618b8225efd92d-reproduction
    - name: Build and push 5cf5a482bd430d81257b4ecd85b3d4f7da911621
      uses: docker/build-push-action@v2
      with:
        context: dataset/5cf5a482bd430d81257b4ecd85b3d4f7da911621/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/5cf5a482bd430d81257b4ecd85b3d4f7da911621/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-5cf5a482bd430d81257b4ecd85b3d4f7da911621-reproduction
    - name: Build and push 1ef97ea6c5b6e34151fe6167001b69e003449f95
      uses: docker/build-push-action@v2
      with:
        context: dataset/1ef97ea6c5b6e34151fe6167001b69e003449f95/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/1ef97ea6c5b6e34151fe6167001b69e003449f95/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-1ef97ea6c5b6e34151fe6167001b69e003449f95-reproduction
    - name: Build and push c7c9590a206d4fb77dd05b9df391d888e6181667
      uses: docker/build-push-action@v2
      with:
        context: dataset/c7c9590a206d4fb77dd05b9df391d888e6181667/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/c7c9590a206d4fb77dd05b9df391d888e6181667/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-c7c9590a206d4fb77dd05b9df391d888e6181667-reproduction
    - name: Build and push ff8b5b61548d50cf60b77784a181e917cb35033b
      uses: docker/build-push-action@v2
      with:
        context: dataset/ff8b5b61548d50cf60b77784a181e917cb35033b/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/ff8b5b61548d50cf60b77784a181e917cb35033b/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-ff8b5b61548d50cf60b77784a181e917cb35033b-reproduction
    - name: Build and push 741f3b5e20a91b0e9305ae79261e3c5e64971c98
      uses: docker/build-push-action@v2
      with:
        context: dataset/741f3b5e20a91b0e9305ae79261e3c5e64971c98/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/741f3b5e20a91b0e9305ae79261e3c5e64971c98/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-741f3b5e20a91b0e9305ae79261e3c5e64971c98-reproduction
    - name: Build and push 16ae40b1e17e14ee3ae20ac211647e47399a01a9
      uses: docker/build-push-action@v2
      with:
        context: dataset/16ae40b1e17e14ee3ae20ac211647e47399a01a9/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/16ae40b1e17e14ee3ae20ac211647e47399a01a9/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-16ae40b1e17e14ee3ae20ac211647e47399a01a9-reproduction
    - name: Build and push 165381d26b2c3d2278fde88c16f95807506451fe
      uses: docker/build-push-action@v2
      with:
        context: dataset/165381d26b2c3d2278fde88c16f95807506451fe/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/165381d26b2c3d2278fde88c16f95807506451fe/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-165381d26b2c3d2278fde88c16f95807506451fe-reproduction
    - name: Build and push 7e8c62e2bb21097e563747184636cf8e8934ce98
      uses: docker/build-push-action@v2
      with:
        context: dataset/7e8c62e2bb21097e563747184636cf8e8934ce98/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt
        file: dataset/7e8c62e2bb21097e563747184636cf8e8934ce98/out/reproduction/claude-3-5-sonnet@20240620_augmented_prompt/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/claude-3-5-sonnet@20240620_augmented_prompt-7e8c62e2bb21097e563747184636cf8e8934ce98-reproduction
