name: Check JSON Schema

on:
  push:
    paths:
      - 'dataset/**/*.json'
      - '.github/workflows/check-schemas.yml'
  pull_request:
    paths:
      - 'dataset/**/*.json'

jobs:
  check-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            dataset
            masterthesis
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install check-jsonschema
        run: |
          python -m pip install --upgrade pip
          pip install check-jsonschema

      - name: Validate JSON files against schema
        run: |
          find dataset -type f -path 'dataset/*/out/*-execution-errors.json' | xargs check-jsonschema --schemafile masterthesis/dataset/dataset_schema.json
