fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: black
        name: black
        entry: pdm run black
        language: system
        types: [file, python]
  # - repo: https://github.com/python-poetry/poetry
  #   rev: '1.8.3'
  #   hooks:
  #   -   id: poetry-check
  #   -   id: poetry-lock
  #   -   id: poetry-install
  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  # - repo: https://github.com/PyCQA/prospector
  #   rev: v1.10.3
  #   hooks:
  #     - id: prospector
  #       args: [
  #       '--with-tool=mypy',
  #       '--with-tool=bandit',
  #       ]
